name: space
favicon: null
layout_spectrum: 1
typography_spectrum: 0.49282
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#512642'
    - '#766498'
    - '#aa344c'
    - '#b07342'
    - '#e0889e'
  brandStrength: 1
  lightness: 0.3125
  saturation: 0.625
  rhythmicContrast: 0.5866097528487444
purpose: []
