name: space
favicon: null
layout_spectrum: 0.73123
typography_spectrum: 0.6880239511374384
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.5
  lightness: 0.1531625036150217
  saturation: 0.46017469209618866
  rhythmicContrast: 0.5866097528487444
purpose: []
