name: space
favicon: null
layout_spectrum: 0
typography_spectrum: 0.39641
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#002d37'
    - '#a2af77'
    - '#71966a'
    - '#d6c07c'
    - '#005451'
  brandStrength: 0.8125
  lightness: 0.75
  saturation: 1
  rhythmicContrast: 0.75
purpose: []
